/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Logica.Fachada_Grafica_Logica;

/**
 *
 * @author 44777219
 */
public class VentanaPartida extends javax.swing.JFrame {

    public static int LBL_MUESTRA = 1;
    public static int LBL_MANO_HUM_1 = 2;
    public static int LBL_MANO_HUM_2 = 3;
    public static int LBL_MANO_HUM_3 = 4;
    public static int LBL_MANO_IA_1 = 5;
    public static int LBL_MANO_IA_2 = 6;
    public static int LBL_MANO_IA_3 = 7;
    public static int LBL_ACTIVA_IA = 8;
    public static int LBL_ACTIVA_HUM = 9;

    /**
     * Creates new form VentanaPartida
     */
    public VentanaPartida() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    //metodos para cargar texto a las label(es de prueba)
    public void cargar_lbl(String texto, int lbl) {
        switch (lbl) {
            case 1://muestra
                lbl_carta_muestra.setText(texto);
                break;
            case 2://mano hum 1
                lbl_carta_hum_1.setText(texto);
                break;
            case 3://mano hum 2
                lbl_carta_hum_2.setText(texto);
                break;
            case 4://mano hum 3
                lbl_carta_hum_3.setText(texto);
                break;
            case 5://mano ia 1
                lbl_carta_ia_1.setText(texto);
                break;
            case 6://mano ia 2
                lbl_carta_ia_2.setText(texto);
                break;
            case 7://mano ia 3
                lbl_carta_ia_3.setText(texto);
                break;
            case 8://ACTIVA IA
                lbl_carta_activa_ia.setText(texto);
                break;
            case 9://ACTIVA HUMANO
                lbl_carta_activa_humano.setText(texto);
                break;

        }
    }

    public void actualizar_cartas_lbl() {
        Fachada_Grafica_Logica fgl = Fachada_Grafica_Logica.getSingletonInstancia();
        cargar_lbl(fgl.partida.getMuestra().toString(), VentanaPartida.LBL_MUESTRA);
        cargar_lbl(fgl.partida.getMano_humano().getCartas_mano()[0].toString(), VentanaPartida.LBL_MANO_HUM_1);
        cargar_lbl(fgl.partida.getMano_humano().getCartas_mano()[1].toString(), VentanaPartida.LBL_MANO_HUM_2);
        cargar_lbl(fgl.partida.getMano_humano().getCartas_mano()[2].toString(), VentanaPartida.LBL_MANO_HUM_3);
        cargar_lbl(fgl.partida.getMano_ia().getCartas_mano()[0].toString(), VentanaPartida.LBL_MANO_IA_1);
        cargar_lbl(fgl.partida.getMano_ia().getCartas_mano()[1].toString(), VentanaPartida.LBL_MANO_IA_2);
        cargar_lbl(fgl.partida.getMano_ia().getCartas_mano()[2].toString(), VentanaPartida.LBL_MANO_IA_3);
        
    }

    public void actualizar_puntajes(int pts_humano, int pts_ia) {
        lbl_pts_yo.setText(String.valueOf(pts_humano));
        lbl_pts_el.setText(String.valueOf(pts_ia));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        panel_mano_ia = new javax.swing.JPanel();
        lbl_carta_ia_1 = new javax.swing.JLabel();
        lbl_carta_ia_2 = new javax.swing.JLabel();
        lbl_carta_ia_3 = new javax.swing.JLabel();
        panel_mazo = new javax.swing.JPanel();
        lbl_mazo1 = new javax.swing.JLabel();
        panel_mano_humano = new javax.swing.JPanel();
        lbl_carta_hum_1 = new javax.swing.JLabel();
        lbl_carta_hum_2 = new javax.swing.JLabel();
        lbl_carta_hum_3 = new javax.swing.JLabel();
        panel_tanteador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_yo = new javax.swing.JLabel();
        lbl_el = new javax.swing.JLabel();
        lbl_pts_el = new javax.swing.JLabel();
        lbl_pts_yo = new javax.swing.JLabel();
        lbl_carta_activa_ia = new javax.swing.JLabel();
        lbl_carta_activa_humano = new javax.swing.JLabel();
        lbl_carta_muestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panel_fondo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel_fondo.setMaximumSize(new java.awt.Dimension(150, 200));
        panel_fondo.setMinimumSize(new java.awt.Dimension(150, 200));
        panel_fondo.setPreferredSize(new java.awt.Dimension(150, 200));
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_mano_ia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_mano_ia.setMaximumSize(new java.awt.Dimension(500, 200));
        panel_mano_ia.setMinimumSize(new java.awt.Dimension(500, 200));

        lbl_carta_ia_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_ia_1.setText("Carta ia 1");
        lbl_carta_ia_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_carta_ia_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_ia_2.setText("Carta ia 2");
        lbl_carta_ia_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_carta_ia_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_ia_3.setText("Carta ia 3");
        lbl_carta_ia_3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_mano_iaLayout = new javax.swing.GroupLayout(panel_mano_ia);
        panel_mano_ia.setLayout(panel_mano_iaLayout);
        panel_mano_iaLayout.setHorizontalGroup(
            panel_mano_iaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mano_iaLayout.createSequentialGroup()
                .addComponent(lbl_carta_ia_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_carta_ia_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_carta_ia_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_mano_iaLayout.setVerticalGroup(
            panel_mano_iaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_carta_ia_1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addComponent(lbl_carta_ia_3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addComponent(lbl_carta_ia_2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );

        panel_fondo.add(panel_mano_ia, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));

        panel_mazo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_mazo.setMaximumSize(new java.awt.Dimension(150, 200));
        panel_mazo.setMinimumSize(new java.awt.Dimension(150, 200));
        panel_mazo.setPreferredSize(new java.awt.Dimension(150, 200));

        lbl_mazo1.setText("MAZO");

        javax.swing.GroupLayout panel_mazoLayout = new javax.swing.GroupLayout(panel_mazo);
        panel_mazo.setLayout(panel_mazoLayout);
        panel_mazoLayout.setHorizontalGroup(
            panel_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mazoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_mazo1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_mazoLayout.setVerticalGroup(
            panel_mazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mazoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_mazo1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_fondo.add(panel_mazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        panel_mano_humano.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_mano_humano.setMaximumSize(new java.awt.Dimension(500, 200));
        panel_mano_humano.setMinimumSize(new java.awt.Dimension(500, 200));
        panel_mano_humano.setPreferredSize(new java.awt.Dimension(500, 200));

        lbl_carta_hum_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_hum_1.setText("Carta hum 1");
        lbl_carta_hum_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_carta_hum_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_hum_2.setText("Carta hum 2");
        lbl_carta_hum_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_carta_hum_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_hum_3.setText("Carta hum 3");
        lbl_carta_hum_3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_mano_humanoLayout = new javax.swing.GroupLayout(panel_mano_humano);
        panel_mano_humano.setLayout(panel_mano_humanoLayout);
        panel_mano_humanoLayout.setHorizontalGroup(
            panel_mano_humanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mano_humanoLayout.createSequentialGroup()
                .addComponent(lbl_carta_hum_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_carta_hum_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_carta_hum_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_mano_humanoLayout.setVerticalGroup(
            panel_mano_humanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_carta_hum_1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(lbl_carta_hum_3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(lbl_carta_hum_2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        panel_fondo.add(panel_mano_humano, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 456, -1, -1));

        jLabel1.setText("lbl_tanteador");

        lbl_yo.setText("Yo");

        lbl_el.setText("Él");

        lbl_pts_el.setText("pts");

        lbl_pts_yo.setText("pts");

        javax.swing.GroupLayout panel_tanteadorLayout = new javax.swing.GroupLayout(panel_tanteador);
        panel_tanteador.setLayout(panel_tanteadorLayout);
        panel_tanteadorLayout.setHorizontalGroup(
            panel_tanteadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tanteadorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_tanteadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tanteadorLayout.createSequentialGroup()
                        .addComponent(lbl_yo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lbl_el, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_tanteadorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_pts_yo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_pts_el, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tanteadorLayout.setVerticalGroup(
            panel_tanteadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tanteadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_tanteadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_yo)
                    .addComponent(lbl_el))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_tanteadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pts_el, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pts_yo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_fondo.add(panel_tanteador, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 150, -1));

        lbl_carta_activa_ia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_activa_ia.setText("ACTIVA IA");
        lbl_carta_activa_ia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_carta_activa_ia.setMaximumSize(new java.awt.Dimension(150, 200));
        lbl_carta_activa_ia.setMinimumSize(new java.awt.Dimension(150, 200));
        lbl_carta_activa_ia.setPreferredSize(new java.awt.Dimension(150, 200));
        panel_fondo.add(lbl_carta_activa_ia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 150, 190));

        lbl_carta_activa_humano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_carta_activa_humano.setText("ACTIVA HUMANO");
        lbl_carta_activa_humano.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_fondo.add(lbl_carta_activa_humano, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 150, 190));

        lbl_carta_muestra.setText("MUESTRA");
        lbl_carta_muestra.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_carta_muestra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_carta_muestra.setMaximumSize(new java.awt.Dimension(150, 200));
        lbl_carta_muestra.setMinimumSize(new java.awt.Dimension(150, 200));
        lbl_carta_muestra.setPreferredSize(new java.awt.Dimension(150, 200));
        panel_fondo.add(lbl_carta_muestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 150, 190));

        getContentPane().add(panel_fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_carta_activa_humano;
    private javax.swing.JLabel lbl_carta_activa_ia;
    private javax.swing.JLabel lbl_carta_hum_1;
    private javax.swing.JLabel lbl_carta_hum_2;
    private javax.swing.JLabel lbl_carta_hum_3;
    private javax.swing.JLabel lbl_carta_ia_1;
    private javax.swing.JLabel lbl_carta_ia_2;
    private javax.swing.JLabel lbl_carta_ia_3;
    private javax.swing.JLabel lbl_carta_muestra;
    private javax.swing.JLabel lbl_el;
    private javax.swing.JLabel lbl_mazo1;
    private javax.swing.JLabel lbl_pts_el;
    private javax.swing.JLabel lbl_pts_yo;
    private javax.swing.JLabel lbl_yo;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPanel panel_mano_humano;
    private javax.swing.JPanel panel_mano_ia;
    private javax.swing.JPanel panel_mazo;
    private javax.swing.JPanel panel_tanteador;
    // End of variables declaration//GEN-END:variables
}
